export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const CHANGE_SEARCH_FIELD_AGE = 'CHANGE_SEARCH_FIELD_AGE';

export const REQUEST_PLAYERS_PENDING = 'REQUESTS_PLAYERS_PENDING';
export const REQUEST_PLAYERS_SUCCESS = 'REQUESTS_PLAYERS_SUCCESS';
export const REQUEST_PLAYERS_FAILED = 'REQUESTS_PLAYERS_FAILED';
